import numpy as np
import logging
from scipy.stats import ks_2samp
from scipy.spatial.distance import cdist

# Configure module-level logging for validation events
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s - %(message)s")
logger = logging.getLogger("PrivacyValidator")

class PrivacyValidator:
    """
    Validates synthetic data generated by the VAE.
    Enforces a strict two-gate validation pipeline:
    1. Statistical Utility: Ensures the synthetic data distribution matches the real data.
    2. Privacy Guarantee: Ensures the VAE did not memorize and replicate exact real records.
    """
    def __init__(self, ks_threshold: float = 0.1, privacy_distance_threshold: float = 1e-4):
        """
        Args:
            ks_threshold: The maximum allowed Kolmogorov-Smirnov statistic. 
                          Lower values demand tighter statistical alignment between distributions.
            privacy_distance_threshold: The minimum allowed Euclidean distance between a 
                                        synthetic record and its nearest real neighbor. 
                                        Prevents exact or near-exact memorization.
        """
        self.ks_threshold = ks_threshold
        self.privacy_distance_threshold = privacy_distance_threshold

    def validate_data(self, real_data: np.ndarray, synthetic_data: np.ndarray) -> bool:
        """
        The main orchestration method for the validation pipeline.
        Data only passes if it satisfies both the utility and privacy constraints.
        """
        logger.info("Initiating Self-Validation Loop...")
        
        # Gate 1: Check if the data is statistically useful
        is_statistically_sound = self._check_statistical_utility(real_data, synthetic_data)
        
        # Gate 2: Check if the data is mathematically private
        is_private = self._check_privacy_leakage(real_data, synthetic_data)
        
        if is_statistically_sound and is_private:
            logger.info("[SUCCESS] Synthetic data passed both Utility and Privacy checks.")
            return True
        else:
            logger.warning("[FAILED] Synthetic data rejected. VAE requires further training or tuning.")
            return False

    def _check_statistical_utility(self, real_data: np.ndarray, synthetic_data: np.ndarray) -> bool:
        """
        Evaluates the statistical similarity feature-by-feature using the Kolmogorov-Smirnov (KS) test.
        The KS test quantifies the maximum distance between the cumulative distribution 
        functions (CDF) of the two samples.
        """
        num_features = real_data.shape[1]
        
        for feature_idx in range(num_features):
            real_col = real_data[:, feature_idx]
            synth_col = synthetic_data[:, feature_idx]
            
            # ks_2samp returns the KS statistic and the p-value.
            # The statistic represents the maximum absolute distance between the two CDFs.
            ks_stat, p_value = ks_2samp(real_col, synth_col)
            
            if ks_stat > self.ks_threshold:
                logger.debug(
                    f"Feature {feature_idx} failed KS test. "
                    f"Stat: {ks_stat:.4f} > Threshold: {self.ks_threshold}"
                )
                return False
                
        logger.info("[PASS] Statistical Utility Check: Distributions align within acceptable margins.")
        return True

    def _check_privacy_leakage(self, real_data: np.ndarray, synthetic_data: np.ndarray) -> bool:
        """
        Evaluates the Distance to Closest Record (DCR).
        Calculates the Euclidean distance between every synthetic record and every real record.
        If any synthetic record is too close to a real record, it indicates the VAE overfitted 
        and memorized the raw data, constituting a privacy breach.
        """
        # cdist computes the distance matrix between the two data arrays.
        # Shape of distances: (num_synthetic_samples, num_real_samples)
        distances = cdist(synthetic_data, real_data, metric='euclidean')
        
        # For each synthetic record, find the distance to its single closest real neighbor
        min_distances = np.min(distances, axis=1)
        
        # Identify how many synthetic records violate the privacy threshold
        privacy_breaches = np.sum(min_distances < self.privacy_distance_threshold)
        
        if privacy_breaches > 0:
            logger.error(
                f"[FAIL] PRIVACY BREACH: {privacy_breaches} synthetic records "
                f"are too close (memorized) to real user data."
            )
            return False
            
        logger.info("[PASS] Privacy Check: No exact or near-exact raw data replication detected.")
        return True