import logging
import subprocess
import uuid
from pathlib import Path
from typing import Optional

#configure module-level logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s"
)
logger = logging.getLogger("DynamicAgentFactory")

class DynamicAgentFactory:
    """
    Factory class responsible for materializing and executing dynamically 
    generated Python agents within a secure, containerized sandbox environment.
    """

    def __init__(self, logs_dir: str = "./raw_data"):
        """
        Initializes the factory and ensures the output directory exists.
        
        Args:
            logs_dir (str): The local directory where the sandboxed agent 
                            will write its collected raw data.
        """
        #using pathlib for robust cross-platform path handling
        self.logs_dir = Path(logs_dir).resolve()
        #like the command create a directory, create missing parents directories (parents=True) and if the directroy already exist do not raise an error (exist_ok = True)
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        
        #temp directory for storing the dynamically generated scripts
        self.temp_dir = Path("./temp_agents").resolve()
        #the same as the above 
        self.temp_dir.mkdir(parents=True, exist_ok=True)

    def generate_and_execute(self, llm_generated_code: str, execution_timeout: int = 60) -> bool:
        """
        Saves the generated code to a temporary file and executes it via Docker.
        
        Args:
            llm_generated_code (str): The Python script produced by the LLM.
            execution_timeout (int): Maximum allowed execution time in seconds.
            
        Returns:
            bool: True if the agent executed successfully and exited with code 0, False otherwise.
        """
        
        #give the agent unique name 
        agent_id = f"agent_{uuid.uuid4().hex[:8]}"
        #the file of the agent to run 
        script_path = self.temp_dir / f"{agent_id}.py"
        
        try:
            # materialize the code to disk (actually write it)
            script_path.write_text(llm_generated_code, encoding="utf-8")
            logger.info(f"Materialized dynamic agent '{agent_id}' at {script_path}")
            
            # prepare the secure Docker execution command (for not running code generated by LLM on the machine)
            # Security Note: We restrict memory and CPU to prevent resource exhaustion (Denial of Service)
            # we map the script file as Read-Only (ro) and the logs directory as Read-Write (rw).
            docker_cmd = [
                "docker", "run", "--rm",
                "--memory=256m", 
                "--cpus=0.5",
                "-v", f"{script_path}:/app/agent.py:ro",
                "-v", f"{self.logs_dir}:/app/logs:rw",
                "-w", "/app",
                "python:3.9-slim",
                "python", "agent.py"
            ]
            
            logger.info(f"Initiating sandboxed execution for '{agent_id}'...")
            
            #execute with a timeout (parameter)
            result = subprocess.run(
                docker_cmd, 
                capture_output=True, 
                text=True, 
                timeout=execution_timeout
            )
            
            if result.returncode == 0:
                logger.info(f"Agent '{agent_id}' executed successfully. Data is ready in {self.logs_dir}.")
                return True
            else:
                logger.error(f"Agent '{agent_id}' failed with exit code {result.returncode}.")
                logger.error(f"Agent Stderr:\n{result.stderr.strip()}")
                return False
                
        except subprocess.TimeoutExpired:
            logger.warning(f"Execution of agent '{agent_id}' timed out after {execution_timeout} seconds.")
            return False
        except Exception as e:
            logger.critical(f"Unexpected error during agent execution: {e}")
            return False
        finally:
            #Cleanup: ensure the temporary script is deleted regardless of success or failure
            self._cleanup_temp_file(script_path)

    def _cleanup_temp_file(self, file_path: Path) -> None:
        """
        Securely removes the temporary script file from the host filesystem.
        """
        if file_path.exists():
            try:
                file_path.unlink()
                logger.debug(f"Successfully cleaned up {file_path}")
            except Exception as e:
                logger.error(f"Failed to delete temporary script {file_path}: {e}")